# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ortaman
# "service" is the name of this project. This will also be added to your AWS resource names.
service: forte-api

custom:
  wsgi:
    app: forte-api/app.app

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  crud:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

    environment:
      MONGO_NAME: forte-db
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_COLLECT_NAME: transactions
      MONGO_HOST: localhost
 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
 