# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ortaman
# "service" is the name of this project. This will also be added to your AWS resource names.
service: forte-api

custom:
  wsgi:
    app: forte-api/app.app

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  crud:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

    environment:
      MONGO_NAME: forte-db
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: localhost
      MONGO_DEFAULT_COLLECTION: transactions
      
  txns_resume:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /transactions/resume
          method: GET

    environment:
      MONGO_NAME: forte-db
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: localhost
      MONGO_DEFAULT_COLLECTION: transactions

  txns_download_xlsx:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /transactions/xlsx
          method: GET

    environment:
      MONGO_NAME: forte-db
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: localhost
      MONGO_DEFAULT_COLLECTION: transactions

  txns_save_xlsx:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /transactions/xlsx
          method: POST

    environment:
      MONGO_NAME: forte-db
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: localhost
      MONGO_DEFAULT_COLLECTION: transactions

      S3_NAME: forte-test-bucket
      B3_ACC: AKIATTSKFN7QZJFSSR6G
      B3_SEC: zzQw/J8jm9f0ABWnVg60T2eLeIlKTD7mgtkQFBb1

plugins:
  - serverless-wsgi
  - serverless-python-requirements
 